env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-1-snap
      image_family: freebsd-12-1
      image_family: freebsd-12-0
      image_family: freebsd-11-3-snap
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y autoconf automake curl lcov libtool
  script:
    - ./autogen.sh && ./configure --enable-urls --enable-coverage && make && make check
